import { useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { AlertTriangle, Plus } from 'lucide-react'
import { addFault, addMaintenance, getEquipment, getFaults, updateEquipment } from '../lib/store'
import StatusBadge from '../components/StatusBadge'

export default function Faults(){const loc=useLocation();const [faults,setFaults]=useState([]),[equipment,setEquipment]=useState([]),[open,setOpen]=useState(Boolean(loc.state?.equipment));const [form,setForm]=useState({equipment_id:loc.state?.equipment?.id||'',priority:'medium',description:''});
 const load=()=>Promise.all([getFaults(),getEquipment()]).then(([f,e])=>{setFaults(f);setEquipment(e)});useEffect(load,[])
 async function submit(e){e.preventDefault();const eq=equipment.find(x=>x.id===form.equipment_id);if(!eq)return;await addFault({...form,asset_id:eq.asset_id,equipment_name:eq.name,reported_by:'Current user'});await addMaintenance({equipment_id:eq.id,asset_id:eq.asset_id,equipment_name:eq.name,type:'corrective',title:`Corrective action: ${form.description.slice(0,50)}`,priority:form.priority,status:'assigned',assigned_to:'Rahul Technician',due_date:new Date(Date.now()+86400000*2).toISOString().slice(0,10),cost:0});await updateEquipment(eq.id,{status:'maintenance'});setOpen(false);setForm({equipment_id:'',priority:'medium',description:''});load()}
 return <><div className="page-heading"><div><p className="eyebrow">INCIDENT MANAGEMENT</p><h1>Fault reports</h1><p>Capture problems and turn them into corrective maintenance work.</p></div><button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> Report fault</button></div>{open&&<form className="panel fault-form" onSubmit={submit}><h3>New fault report</h3><label>Equipment<select required value={form.equipment_id} onChange={e=>setForm(x=>({...x,equipment_id:e.target.value}))}><option value="">Select equipment</option>{equipment.map(x=><option key={x.id} value={x.id}>{x.asset_id} — {x.name}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm(x=>({...x,priority:e.target.value}))}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Description<textarea required rows="4" value={form.description} onChange={e=>setForm(x=>({...x,description:e.target.value}))}/></label><div className="form-actions"><button type="button" className="ghost-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn">Submit & create maintenance task</button></div></form>}
 <div className="panel"><div className="table-wrap"><table><thead><tr><th>Equipment</th><th>Description</th><th>Priority</th><th>Status</th><th>Reported</th></tr></thead><tbody>{faults.map(f=><tr key={f.id}><td><b>{f.asset_id}</b><br/><span className="muted">{f.equipment_name}</span></td><td>{f.description}</td><td><StatusBadge value={f.priority}/></td><td><StatusBadge value={f.status}/></td><td>{new Date(f.reported_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></div></>}
