import { useEffect, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { CheckCircle2, PlayCircle, Plus } from 'lucide-react'
import { addMaintenance, getEquipment, getMaintenance, updateEquipment, updateMaintenance } from '../lib/store'
import StatusBadge from '../components/StatusBadge'

export default function Maintenance(){const loc=useLocation();const [tasks,setTasks]=useState([]),[equipment,setEquipment]=useState([]),[open,setOpen]=useState(Boolean(loc.state?.equipment));const [f,setF]=useState({equipment_id:loc.state?.equipment?.id||'',title:'Preventive maintenance',priority:'medium',due_date:''});const load=()=>Promise.all([getMaintenance(),getEquipment()]).then(([m,e])=>{setTasks(m);setEquipment(e)});useEffect(load,[])
 async function create(e){e.preventDefault();const eq=equipment.find(x=>x.id===f.equipment_id);await addMaintenance({...f,equipment_name:eq.name,asset_id:eq.asset_id,type:'preventive',status:'scheduled',assigned_to:'Rahul Technician',cost:0});setOpen(false);load()}
 async function setStatus(t,status){await updateMaintenance(t.id,{status}); if(status==='in_progress') await updateEquipment(t.equipment_id,{status:'maintenance'}); if(status==='completed') await updateEquipment(t.equipment_id,{status:'available'});load()}
 return <><div className="page-heading"><div><p className="eyebrow">SERVICE OPERATIONS</p><h1>Maintenance</h1><p>Schedule preventive work and manage technician tasks.</p></div><button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> Schedule maintenance</button></div>{open&&<form className="panel form-grid compact" onSubmit={create}><label>Equipment<select required value={f.equipment_id} onChange={e=>setF(x=>({...x,equipment_id:e.target.value}))}><option value="">Select equipment</option>{equipment.map(x=><option key={x.id} value={x.id}>{x.asset_id} — {x.name}</option>)}</select></label><label>Task title<input value={f.title} onChange={e=>setF(x=>({...x,title:e.target.value}))}/></label><label>Priority<select value={f.priority} onChange={e=>setF(x=>({...x,priority:e.target.value}))}><option>low</option><option>medium</option><option>high</option></select></label><label>Due date<input required type="date" value={f.due_date} onChange={e=>setF(x=>({...x,due_date:e.target.value}))}/></label><div className="full form-actions"><button type="button" className="ghost-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn">Create task</button></div></form>}
 <div className="maintenance-board">{['scheduled','assigned','in_progress','completed'].map(col=><section className="kanban-col" key={col}><h3>{col.replace('_',' ')}</h3>{tasks.filter(t=>t.status===col).map(t=><article className="task-card" key={t.id}><div className="row-between"><b>{t.asset_id}</b><StatusBadge value={t.priority}/></div><h4>{t.title}</h4><p>{t.equipment_name}</p><span className="muted">Due {t.due_date||'—'}</span><div className="task-actions">{['scheduled','assigned'].includes(t.status)&&<button onClick={()=>setStatus(t,'in_progress')}><PlayCircle size={15}/> Start</button>}{t.status==='in_progress'&&<button onClick={()=>setStatus(t,'completed')}><CheckCircle2 size={15}/> Complete</button>}</div></article>)}</section>)}</div></>}
